// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALXika9IX_6_Tu7kxPhtOucwOOgoGWAQE',
    appId: '1:1055802094446:web:d4b8a57e1aa003941b477f',
    messagingSenderId: '1055802094446',
    projectId: 'mytodo-b47f9',
    authDomain: 'mytodo-b47f9.firebaseapp.com',
    storageBucket: 'mytodo-b47f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-ToXMtF3kKPt-I7_JranpI4_jzS78p8',
    appId: '1:1055802094446:android:1671db2381a2d8631b477f',
    messagingSenderId: '1055802094446',
    projectId: 'mytodo-b47f9',
    storageBucket: 'mytodo-b47f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPWZ_finFINvF6RP_ItWGwiHC1fUTbFno',
    appId: '1:1055802094446:ios:899f065d9c1c3cde1b477f',
    messagingSenderId: '1055802094446',
    projectId: 'mytodo-b47f9',
    storageBucket: 'mytodo-b47f9.appspot.com',
    iosClientId: '1055802094446-gmmh66ivoshfl3f6e71fdn75qmk30sho.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPWZ_finFINvF6RP_ItWGwiHC1fUTbFno',
    appId: '1:1055802094446:ios:899f065d9c1c3cde1b477f',
    messagingSenderId: '1055802094446',
    projectId: 'mytodo-b47f9',
    storageBucket: 'mytodo-b47f9.appspot.com',
    iosClientId: '1055802094446-gmmh66ivoshfl3f6e71fdn75qmk30sho.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodo',
  );
}
